linters-settings:
  govet:
    enable:
      - appends
      - asmdecl
      - assign
      - atomic
      - atomicalign
      - bools
      - buildtag
      - cgocall
      - composites
      - copylocks
      - deepequalerrors
      - defers
      - directive
      - errorsas
      - fieldalignment
      - findcall
      - framepointer
      - httpresponse
      - ifaceassert
      - loopclosure
      - lostcancel
      - nilfunc
      - nilness
      - printf
      - reflectvaluecompare
      - shadow
      - shift
      - sigchanyzer
      - slog
      - sortslice
      - stdmethods
      - stringintconv
      - structtag
      - testinggoroutine
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
      - unusedwrite

  gofmt:
    rewrite-rules:
      - pattern: interface{}
        replacement: any

  depguard:
    rules:
      main:
        deny:
          - pkg: "sync/atomic"
            desc: use uber atomic package

linters:
  # See the dedicated "linters" documentation section.
  enable:
    - govet
    - exhaustive
    - depguard

  disable:
    - errcheck
    - unused
  fast: true

issues:
  exclude-rules:
    - path: internal/web/jsonrpc/
      linters:
        - govet
