default_language_version:
  python: python3.14

repos:
  - repo: https://github.com/trim21/dprint-pre-commit
    rev: "v0.53.1.0"
    hooks:
      - id: dprint
        pass_filenames: false
        always_run: true
