services:
  tyr:
    image: ghcr.io/trim21/tyr:master
    environment:
      TYR_LOG_LEVEL: debug
      TYR_WEB_SECRET_TOKEN: a-random-token
      TYR_SESSION_PATH: '/var/lib/tyr'
      TYR_CONFIG_FILE: '/var/lib/config/tyr.toml'
    network_mode: host
    healthcheck:
      test: [ "CMD", "/usr/bin/wget", "--no-verbose", "http://127.0.0.1:8002/healthz" ]
      interval: 30s
      timeout: 3s
      retries: 1
      start_period: 30s
    volumes:
      # keep this in sync with flood container mount config
      - ./data/tyr/:/var/lib/tyr/

      # keep this in sync with flood container mount config
      - ./data/downloads/:/downloads/

      - ./config.toml:/var/lib/config/tyr.toml:ro

#  flood:
#    image: 'jesec/flood:latest'
#    ports:
#      - 3000:3000
#    volumes:
#      # keep this in sync with tyr container mount config
#      - ./data/tyr/:/var/lib/tyr/
#
#      # keep this in sync with tyr container mount config
#      - ./data/downloads/:/downloads/
