services:
  tyr:
    image: ghcr.io/trim21/tyr:master
    init: true
    environment:
      TYR_DEBUG: true
      TYR_LOG_LEVEL: debug
      TYR_WEB_SECRET_TOKEN: a-secret-token
      TYR_SESSION_PATH: '/var/lib/tyr'
      TYR_CONFIG_FILE: '/var/lib/config/tyr.toml'
    network_mode: host
    healthcheck:
      test: [ "CMD", "/usr/local/bin/wget", "--spider", "--no-verbose", "http://127.0.0.1:8002/healthz" ]
      interval: 10s
      timeout: 3s
      start_period: 10s
    volumes:
      # keep this in sync with flood container mount config
      - ./data/tyr/:/var/lib/tyr/

      # keep this in sync with flood container mount config
      - ./data/downloads/:/downloads/

      - ./config.toml:/var/lib/config/tyr.toml:ro

  flood:
    image: 'ghcr.io/trim21/flood:tyr'
    network_mode: host
    command:
      - --port=4008 # flood web-ui port
      - --noauth
      - --tyr-url=http://127.0.0.1:8002/json_rpc
      - --tyr-token=a-secret-token
    volumes:
      # keep this in sync with tyr container mount config
      - ./data/tyr/:/var/lib/tyr/

      # keep this in sync with tyr container mount config
      - ./data/downloads/:/downloads/
