services:
  neptune:
    image: ghcr.io/trim21/neptune:master
    init: true
    environment:
      NEPTUNE_DEBUG: true
      NEPTUNE_LOG_LEVEL: debug
      NEPTUNE_WEB_SECRET_TOKEN: a-secret-token
      NEPTUNE_SESSION_PATH: "/var/lib/neptune"
      NEPTUNE_CONFIG_FILE: "/var/lib/config/neptune.toml"
    network_mode: host
    healthcheck:
      test: [
        "CMD",
        "/usr/local/bin/wget",
        "--spider",
        "--no-verbose",
        "http://127.0.0.1:8002/healthz",
      ]
      interval: 10s
      timeout: 3s
      start_period: 10s
    volumes:
      # keep this in sync with flood container mount config
      - ./data/neptune/:/var/lib/neptune/

      # keep this in sync with flood container mount config
      - ./data/downloads/:/downloads/

      - ./config.toml:/var/lib/config/neptune.toml:ro

  flood:
    image: "ghcr.io/trim21/flood:neptune"
    network_mode: host
    command:
      - --port=4008 # flood web-ui port
      - --noauth
      - --neptune-url=http://127.0.0.1:8002/json_rpc
      - --neptune-token=a-secret-token
    volumes:
      # keep this in sync with neptune container mount config
      - ./data/neptune/:/var/lib/neptune/

      # keep this in sync with neptune container mount config
      - ./data/downloads/:/downloads/
