name: autofix.ci

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

env:
  GOTOOLCHAIN: "local"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: curl -fsSL https://dprint.dev/install.sh | sh -
      - run: echo "/home/runner/.dprint/bin" >> $GITHUB_PATH
      - run: dprint fmt **/*

      - uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef
