name: build

on:
  push:
    paths-ignore:
      - "*.md"
    branches:
      - master
  pull_request:
    paths-ignore:
      - "*.md"
    branches:
      - master

env:
  GOTOOLCHAIN: local

jobs:
  binary:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ github.token }}

      - uses: trim21/actions/setup-go@master
        with:
          cache-namespace: build

      - run: task release

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: neptune
          path: dist

  docker:
    needs: [binary]
    if: ${{ github.event_name == 'push' }}
    runs-on: "ubuntu-latest"
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4
        with:
          name: neptune
          path: dist

      - run: chmod +x ./dist/*

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        with:
          images: "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}"
          tags: |
            type=semver,pattern=v{{version}}

            type=ref,event=branch
            type=ref,event=branch,suffix=-{{ sha }}

            type=raw,value=${{ env.SHA }}

      # need to build for multiple platform in one-pass, so tags like `master` doesn't get messed-up

      - name: Build and push
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6
        with:
          context: .
          push: true
          provenance: false
          file: etc/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
