name: build

on:
  push:
    branches:
      - master

env:
  GOTOOLCHAIN: local

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"
          cache-dependency-path: |
            go.sum
            tools/go.sum

      - run: task build
        env:
          CGO_ENABLED: '0'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          file: etc/Dockerfile
          tags: user/app:latest
