name: "Run TODO to Issue"
on: [ "push" ]
jobs:
  build:
    permissions:
      issues: write
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4"
